# Generated by Django 2.2.5 on 2020-02-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='style',
        ),
        migrations.RemoveField(
            model_name='events',
            name='training',
        ),
    ]
