# Generated by Django 2.2.5 on 2020-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200208_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='leads',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
