# Generated by Django 2.2.5 on 2020-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_events_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='leads',
        ),
    ]
