# Generated by Django 2.2.5 on 2020-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_events_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tab',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
