# Generated by Django 2.2.5 on 2020-02-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200210_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='tablica',
            new_name='tablica1',
        ),
    ]
