# Generated by Django 2.2.5 on 2020-02-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20200210_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='tablica1',
        ),
    ]
