# Generated by Django 2.2.5 on 2020-02-10 17:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_events_tablica1'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tablica1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
