# Generated by Django 2.2.5 on 2020-02-10 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_events_tablica1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='tablica1',
        ),
        migrations.AddField(
            model_name='events',
            name='tablica',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
