# Generated by Django 2.2.5 on 2020-02-10 18:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20200210_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='break_training',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
