# Generated by Django 2.2.5 on 2020-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_events_break_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
